### ISSUE TITLE
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')

### ISSUE THREAD

**Issue by robertherber** [timedtext/expo-config-plugin-ios-share-extension#3]
I run into this error when running prebuild, not quite sure what is the next step. Any ideas?

```
TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Cannot read properties of null (reading 'path')
    at correctForPath (/Users/robertherber/code/schedulist/schedulist-app/node_modules/xcode/lib/pbxProject.js:1682:38)
    at correctForResourcesPath (/Users/robertherber/code/schedulist/schedulist-app/node_modules/xcode/lib/pbxProject.js:1672:12)
    at pbxProject.addResourceFile (/Users/robertherber/code/schedulist/schedulist-app/node_modules/xcode/lib/pbxProject.js:258:9)
    at /Users/robertherber/code/schedulist/schedulist-app/node_modules/expo-config-plugin-ios-share-extension/build/withShareExtensionXcodeTarget.js:37:20
    at async action (/Users/robertherber/code/schedulist/schedulist-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:235:23)
    at async interceptingMod (/Users/robertherber/code/schedulist/schedulist-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
    at async interceptingMod (/Users/robertherber/code/schedulist/schedulist-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
    at async interceptingMod (/Users/robertherber/code/schedulist/schedulist-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
    at async interceptingMod (/Users/robertherber/code/schedulist/schedulist-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
    at async interceptingMod (/Users/robertherber/code/schedulist/schedulist-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
    at async interceptingMod (/Users/robertherber/code/schedulist/schedulist-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
    at async interceptingMod (/Users/robertherber/code/schedulist/schedulist-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
    at async interceptingMod (/Users/robertherber/code/schedulist/schedulist-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
    at async interceptingMod (/Users/robertherber/code/schedulist/schedulist-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
    at async action (/Users/robertherber/code/schedulist/schedulist-app/node_modules/@expo/config-plugins/build/plugins/createBaseMod.js:71:21)
    at async interceptingMod (/Users/robertherber/code/schedulist/schedulist-app/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
```

**Comment by CodingItWrong** [comment]
I think this is related to this open expo-cli issue: https://github.com/expo/expo-cli/issues/4293

If/when that's fixed it may resolve this. But not sure of any workaround until then.

**Comment by timedtext** [comment]
This is a bug in `xcode`.
We need to use [patch package](https://github.com/ds300/patch-package) to fix this.
I have tried to fix this [here](https://github.com/timedtext/expo-config-plugin-ios-share-extension/blob/69a73811a1a17a161412891742d5631f6c4aacda/patches/xcode%2B3.0.1.patch#L1), but it doesn't work, you need to patch-package in your own project.

**Comment by matthijn** [comment]
First off, thanks for making this package. A bunch of people seem to ask for it, but expo hasn't made one available so far.

I think it would be good if you add (for now) to the readme that the patch needs to be applied and which steps to take. 

eg:

- Run `npm install --save-dev package-patch`
- copy this repo's `patch` folder to the root of the project
- And add `"postinstall": "patch-package"` to the `scripts` section in `package.json`.

Also, another small thing. Currently you only [support urls](https://github.com/timedtext/expo-config-plugin-ios-share-extension/blob/24a68b4e6efbcde4c3485bfec91dad476e0c9933/src/writeShareExtensionFiles.ts#L82). But I think it would be good to [support generic text](https://developer.apple.com/documentation/bundleresources/information_property_list/nsextension/nsextensionattributes/nsextensionactivationrule/nsextensionactivationsupportstext) too. Multiple apps when they share a link, don't exclusively share a url, but prefix it with a title. And here currently this share extension does not show up.

(I guess I can make another patch for that. 😉 But I think it would be useful for more people).

**Comment by matthijn** [comment]
Sorry, removed my other issues and moved them to separate one's.
